
name: Test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x, 22.x ]
        mongo-version: [4, 5, 6]

    steps:
    - uses: actions/checkout@v4

    # 1) Start a Mongo container in replica‐set mode
    - name: Start MongoDB replica set
      run: |
          docker run -d --name mongodb -p 27017:27017 mongo:${{ matrix.mongo-version }} \
            --replSet rs0 --bind_ip_all

    # 2) Initiate the replica set
    - name: Initiate replica set
      run: |
          until docker exec mongodb mongo --eval 'rs.initiate()'; do
            echo "Waiting for Mongo…"
            sleep 1
          done
          
    # 3) Install Node and dependencies
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci

    # 4) Actual running tests
    - run: npm test




    